TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(route = 'admin/', view = admin.site.urls),
    path(route = '', view = include("tasks.urls")),
]

tasks/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path(route = 'admin/', view = admin.site.urls),
    path(route= '',  view = home, name = "home"),
    path(route= 'login/', view = login, name = "login"),
    path(route= 'signup/', view = signup, name = "signup"),
    path(route= 'modify_task', view = modify_task, name = "modify_task"),
    path(route= 'delete', view = delete_task, name = "delete_task"),
    path(route= 'search', view = search, name = "search"),
]

tasks/models.py
from django.db import models
from django.utils.timezone import now


class Member(models.Model):
    first_name = models.CharField(null = False, default = "friend", blank = False, max_length = 30)
    last_name = models.CharField(null = True, max_length = 30)
    assignement = models.CharField(null = True, max_length = 30)
    assignement_description = models.CharField(null = True, max_length = 255)
    

class Task(models.Model):
    SUBJECT_CHOICES = [
        ('Python', 'Python'),
        ('Django', 'Django'),
        ('Linux', 'Linux'),
        ('Networking', 'Networking'),
        ('C_Programming', 'C_Programming'),
        ('Algorythms', 'Algorythms'),
        ('Optimization', 'Optimization'),
        ('Cryptography', 'Cryptography'),
        ('Computer_Architecture', 'Computer_Architecture'),
        ('Data_Structures', 'Data_Structures'),
    ]
    LOCATION_CHOICES = [
        ('Home', 'Home'),
        ('Other', 'Other'),
        ('University', 'University'),
    ]
    title = models.CharField(max_length = 30, null = False, blank = True, default = "task")
    description = models.TextField(max_length = 255, null = True, blank = True, default = title)
    start_time = models.DateTimeField(null = False, default = now)
    end_time = models.DateTimeField(null = True, blank = True)
    time_left = models.DateTimeField(null = True, blank= True)
    location = models.CharField(null = True, max_length = 40, choices = LOCATION_CHOICES, default = 'H')
    subject = models.CharField(null = True, max_length = 30, choices = SUBJECT_CHOICES, default = 'Py')
    members = models.ForeignKey(to = Member, on_delete=models.CASCADE, null = True, blank = True)


class Custom_User(models.Model):
    username = models.CharField(null = False, max_length = 50, unique = True, default = "User")
    password = models.CharField(null = True, max_length = 100, editable = False)
    salt = models.CharField(null = True, max_length = 50, editable = False)
    tasks = models.ManyToManyField(to = Task, related_name= "users", null = True)

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponseBadRequest
from .hash import hash_password, verify_password
from typing import List
from .models import *

"""Summary

"""
def signup(request):
    """This function like signup will be used by 2 forms searches for task in all database
    
        * if Test == True the user signed up and uses the form for redirection to home page
        
        * else the user is soming from the form in index.html and gonna sign up
    """
    if request.method == 'POST' and request.POST.get("Test") != "True":
        username = request.POST.get("username")
        password = request.POST.get("password")
        if Custom_User.objects.filter(username=username).exists():
            message = "Username already exists. Please choose a different one."
            render(request=request, template_name= 'signup.html', context= {'message': message})
        else:
            salt, hashed_pwd = hash_password(password=password)
            user = Custom_User()
            user.username = username
            user.password = hashed_pwd
            user.salt = salt
            user.save()
            return render(request=request, template_name= 'index.html', context= {'user': user})
    return render(request=request, template_name= 'signup.html', context= {})


def login(request):
    if request.method == 'POST':
        if request.POST.get("username") != None and request.POST.get("password") != None:
            username = request.POST.get("username")
            password = request.POST.get("password")
            users = Custom_User.objects.all()
            for user in  users:
                if verify_password(password, user.salt, user.password) == 1:
                    return render(request=request, template_name="index.html", context= {'user': user})
        else:
            return render(request=request, template_name="login.html", context= {})
    return render(request=request, template_name= 'login.html', context= {})
    

def home(request):              # add a method to track time left for each task
    if request.method != 'POST':
        return redirect(to=login)
    else:
        return render(request=request, template_name="index.html", context= {})
    

def delete_task(request): #searches for task in all database
    if request.method != 'POST':
        return redirect(to=login)
    else:
        try:
            task = get_object_or_404(Task, id = int(request.POST.get("id")))
        except Http404:
            return redirect(to= home)
        else:
            task.delete()
            return  
        
    
def modify_task(request):    
    """This function like signup will be used by 2 forms searches for task in all database
    
        * if Test == False the user just used the form in index.html
        
        * else the user updated he values and confirmed the changes
    """
    if request.method != 'POST':
        return redirect(to=login)
    else:
        if request.POST.get("Test") == 'False':

            try:
                task = get_object_or_404(Task, id = int(request.POST.get("id")))
            except Http404:
                return Http404
            else:
                return render(request= request, template_name= "modify_task.html", context={"task": task})
        else:
            #apply modifications made to the task and save
            try:
                task = get_object_or_404(Task, id = int(request.POST.get("id")))
            except Http404:
                return Http404
            else:
                task.title = request.POST.get("title")
                task.description = request.POST.get("description")
                task.location = request.POST.get("location")
                task.subject = request.POST.get("subject")
                task.save()
                return redirect(to= home)
        
def search(request):        #searchs for task in user's tasks
    if request.method == 'POST':
        try:
            user = get_object_or_404(Custom_User, id = int(request.POST.get("id")))
        except Http404:
            return redirect(to= home)
        else:
            tasks = user.tasks.all()
            value = request.POST.get("value")
            for task in tasks:
                if value in task.title:
                     tasks.append(task)
            return render(request= request, template_name= "search.html", context={"tasks": tasks})
    else:
        return redirect(to= login)

tasks/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static '/pictures/mylogo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>Task manager home</title>
</head>
<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" onclick="reloadPage()">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Add tasks</a>
                    </li>
                </ul>
                <form method="post" action="{% url 'search' %}">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{user.id}}" hidden>
                    <input class="form-control me-2"  placeholder="Search" aria-label="Search" name="value">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <table class="table table-hover table-dark">
        <thead class="sticky-top">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Title</th>
                <th scope="col">Start Time</th>
                <th scope="col">Time_left</th>
                <th scope="col">Location</th>
                <th scope="col">Subject</th>
                <th scope="col">Description</th>
                <th scope="col">modify task</th>
                <th scope="col">delete task</th>
            </tr>
        </thead>
        
        <tbody>
            {% for task in user.tasks.all %}
            <tr>
                <th scope="row">{{task.id}}</th>
                <td>{{task.title}}</td>
                <td>{{task.start_time}}</td>
                <td>{{task.time_left}}</td>
                <td>{{task.location}}</td>
                <td>{{task.subject}}</td>
                <td>
                    <button type="button" class="btn btn-light" id="liveToastBtn">Description</button>                    
                    <div class="toast-container position-fixed bottom-0 end-0 p-3">
                        <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                            <div class="toast-header">
                                <img src="..." class="rounded me-2" alt="...">
                                <strong class="me-auto">{{task.title}}</strong>
                                <small>{{task.time_left}}</small>
                                <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                            </div>
                            <div class="toast-body">
                                {{task.description}}
                            </div>
                        </div>
                    </div>                      
                </td>
                <td>
                    <form action="{% url 'modify_task' %}" method="post" target="blank">
                        {% csrf_token %}
                        <input type="hidden" name="Test" value="False" hidden>
                        <input type="hidden" name="id" value="{{task.id}}" hidden>
                        <button type="submit" class="btn btn-light">modify</button>
                    </form>
                </td>
                <td>
                    <form action="{% url 'delete_task' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{task.id}}" hidden>
                        <button type="submit" onclick="reloadPage()" class="btn btn-light">delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        function reloadPage() {
            location.reload(true);
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

tasks/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static '/pictures/mylogo.ico' %}" type="image/x-icon">
    <title>Task manager login</title>
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Login</h3>
                        <center>
                            <p>
                                {{message}}
                            </p>
                        </center>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{% url 'login' %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" class="form-control" id="username" name="username" required>
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                        <center>
                        <form method="post" action="{% url 'signup' %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <input type="hidden" value="True" name="Test" hidden>
                                <button type="submit" class="btn btn-dark">Sign up</button>
                            </div>
                        </form>
                    </center>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

tasks/templates/modify_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static '/pictures/mylogo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>Task Modification</title>
</head>
<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" onclick="reloadPage()">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Add tasks</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    <div class="container">
        <h2>Create or Modify Task</h2>
        <form method="post" action="{% url 'modify_task' %}">
            <input type="hidden" name="id" value="{{task.id}}" hidden>
        {% csrf_token %}
            <!-- Title -->
            <div class="mb-3">
              <label for="id_title" class="form-label">Title</label>
              <input type="text" class="form-control" id="id_title" name="title" maxlength="30" value="{{task.title}}" required>
            </div>

            <!-- Description -->
            <div class="mb-3">
              <label for="id_description" class="form-label">Description</label>
              <textarea class="form-control" id="id_description" name="description" maxlength="255" value="{{task.description}}"></textarea>
            </div>
            <!-- Location -->
            <div class="mb-3">
              <label for="id_location" class="form-label">Location</label>
              <input type="text" class="form-control" id="id_location" name="location" maxlength="40" value="{{task.location}}" required>
            </div>

            <!-- Subject -->
            <div class="mb-3">
              <label for="id_subject" class="form-label">Subject</label>
              <input type="text" class="form-control" id="id_subject" name="subject" maxlength="30" value="{{task.subject}}" required>
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    {% endblock %}
    <script>
        function reloadPage() {
            location.reload(true);
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

tasks/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static '/pictures/mylogo.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>Task manager home</title>
</head>
<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Add tasks</a>
                    </li>
                </ul>
                <form method="post" action="{% url 'search' %}">
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{user.id}}" hidden>
                    <input class="form-control me-2"  placeholder="Search" aria-label="Search" name="value">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <table class="table table-hover table-dark">
        <thead class="sticky-top">
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Title</th>
                <th scope="col">Start Time</th>
                <th scope="col">Time_left</th>
                <th scope="col">Location</th>
                <th scope="col">Subject</th>
                <th scope="col">modify task</th>
                <th scope="col">delete task</th>
            </tr>
        </thead>
        
        <tbody>
            {% for task in tasks %}
            <tr>
                <th scope="row">{{task.id}}</th>
                <td>{{task.title}}</td>
                <td>{{task.start_time}}</td>
                <td>{{task.time_left}}</td>
                <td>{{task.location}}</td>
                <td>{{task.subject}}</td>
                <td>
                    <button type="button" class="btn btn-secondary" data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-bs-content="{{task.description}}">Details</button>
                </td>
                <td>
                    <form action="{% url 'modify_task' %}" method="post" target="blank">
                        {% csrf_token %}
                        <input type="hidden" name="Test" value="False" hidden>
                        <input type="hidden" name="id" value="{{task.id}}" hidden>
                        <button type="submit" class="btn btn-light">modify</button>
                    </form>
                </td>
                <td>
                    <form action="{% url 'delete_task' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{task.id}}" hidden>
                        <button type="submit" onclick="reloadPage()" class="btn btn-light">delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <script>
        function reloadPage() {
            location.reload(true);
        }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

tasks/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="shortcut icon" href="{% static '/pictures/mylogo.ico' %}" type="image/x-icon">
    <title>Task manager Signup</title>
</head>
<body>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Sign up</h3>
                        <center>
                            <p>
                                {{message}}
                            </p>
                        </center>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{% url 'signup' %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" class="form-control" id="username" name="username" required>
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Sign up</button>
                            </div>
                        </form>
                    </div>
                    <div class="card-footer">
                        <center>
                        <form method="post" action="{% url 'login' %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <input type="hidden" value="True" name="Test" hidden>
                                <button type="submit" class="btn btn-dark">Login</button>
                            </div>
                        </form>
                    </center>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>